server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/flipshelf-authdb
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:root}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: 8MYP/eTQUf07DHDAgm8zO8ObGONPPd70P1owqsZBnDDCSYWuO5b0EOGL1aRI4VZnhx3p/1/vD8DXwsfFIJwvzQ==
  expiration: 86400000 # 1 day

logging:
  level:
    org.springframework.security: TRACE
    com.flipshelf.security: DEBUG