global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'flipshelf-auth'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['flipshelf-auth:8081']
        labels:
          application: 'Flipshelf Auth Service'
#  - job_name: 'flipshelf-product'
#    metrics_path: '/actuator/prometheus'
#    static_configs:
#      - targets: ['ms2:8082']
#        labels:
#          application: 'Microservice 2'
#  - job_name: 'ms3'
#    metrics_path: '/actuator/prometheus'
#    static_configs:
#      - targets: ['ms3:8083']
#        labels:
#          application: 'Microservice 3'